package info.introvertische.calculator.basic.enums

enum class ConstantLibrary(val const: String) {
    PI("π"),
    E("e"),
    PLUS("+"),
    MINUS("-"),
    MULTIPLICATION("×"),
    DIVISION("÷"),
    DEGREE("^"),
    SQUARE_ROOT("√"),
    CUBE_ROOT("∛"),
    PERCENT("%"),
    SIN("sin"),
    ARCSIN("sin⁻¹"),
    COS("cos"),
    ARCCOS("cos⁻¹"),
    TG("tg"),
    ARCTG("tg⁻¹"),
    FACTORIAL("!"),
    MOD("mod"),
    MODULE("abs"),
    LOG("log"),
    LN("ln"),
    INVALID_VALUE("FAE"),
}